<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<?php /**/ ?>
<!-- Wrapper -->
	<div id="wrapper" class="divided">

		<!-- Banner -->
			<section class="banner style1 orient-left content-align-left image-position-right fullscreen onload-image-fade-in onload-content-fade-right">
				<div class="content">
					<!-- lang switcher -->
						<ul class="page_lang_selector in_home">
							<li id="lang_globe"><i class="fa fa-globe"></i></li>
							<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
							<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
							<?php }	?>
						</ul>
					<h1><?php echo $title ?></h1>
					<p class="major"><?php echo $abstract ?></p>
					<ul class="actions stacked">
						<li><a href="#first" class="button big wide smooth-scroll-middle"><?php echo tstring('comenzar') ?></a></li>
					</ul>
				</div>
				<div class="image">
					<img src="<?php echo $home_image ?>" />
				</div>
			</section>
		

		<!-- Areas -->
			<?php foreach ($areas_list as $key => $area) { ?>
				<!-- Area header -->
				<section class="wrapper style1 align-center area_header" <?php echo ($key===0) ? 'id="first"' : '' ?> >
					<div class="inner">
						<h2><?php echo $area->title ?></h2>
						<p><?php echo $area->abstract ?></p>
						<?php if (empty($area->childrens)) { ?>
						<ul class="actions stacked">
							<li><a href="<?php echo __WEB_ROOT_WEB__.'/'.$area->web_path ?>" class="button"><?php echo tstring('ver_mas') ?></a></li>
						</ul>
						<?php } ?>
					</div>
				</section>
				<!-- Area children -->
				<?php $i=0; if (!empty($area->childrens)) foreach ($area->childrens as $ckey => $children) {?>
					<section class="spotlight style1 orient-<?php echo !($i % 2 == 0) ? 'right' : 'right white'; #echo !($i % 2 == 0) ? 'right' : 'left' ?> content-align-left image-position-center onscroll-image-fade-in">
						<div class="content">
							<h2><?php echo $children->title ?></h2>
							<p><?php echo $children->abstract ?></p>
							<ul class="actions stacked">
								<li><a href="<?php echo __WEB_ROOT_WEB__.'/'.$children->web_path ?>" class="button"><?php echo tstring('ver_mas') ?></a></li>
							</ul>
						</div>
						<div class="image">
							<a href="<?php echo __WEB_ROOT_WEB__.'/'.$children->web_path ?>" class="">
							<img src="<?php echo $children->image ?>" alt="" />
							</a>
						</div>
					</section>
				<?php $i++; } ?>
			<?php } ?>
		

		<!-- Five -->
			<?php /*
			<section class="wrapper style1 align-center">
				<div class="inner">
					<h2>Massa sed condimentum</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id ante sed ex pharetra lacinia sit amet vel massa. Donec facilisis laoreet nulla eu bibendum. Donec ut ex risus. Fusce lorem lectus, pharetra pretium massa et, hendrerit vestibulum odio lorem ipsum.</p>
				</div>

				<!-- Gallery -->
					<div class="gallery style2 medium lightbox onscroll-fade-in">
						<article>
							<a href="tpl/images/gallery/fulls/01.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/01.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Ipsum Dolor</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/02.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/02.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Feugiat Lorem</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/03.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/03.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Magna Amet</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/04.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/04.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Sed Tempus</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/05.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/05.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Ultrices Magna</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/06.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/06.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Sed Tempus</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/07.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/07.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Ipsum Lorem</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/08.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/08.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Magna Risus</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/09.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/09.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Tempus Dolor</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/10.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/10.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Sed Etiam</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/11.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/11.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Magna Lorem</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
						<article>
							<a href="tpl/images/gallery/fulls/12.jpg" class="image">
								<img src="tpl/images/gallery/thumbs/12.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Ipsum Dolor</h3>
								<p>Lorem ipsum dolor amet, consectetur magna etiam elit. Etiam sed ultrices.</p>
								<ul class="actions fixed">
									<li><span class="button small">Details</span></li>
								</ul>
							</div>
						</article>
					</div>

			</section>
			*/ ?>
		

		<!-- Six -->
			<?php /*
			<section class="wrapper style1 align-center">
				<div class="inner">
					<h2>Ipsum sed consequat</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi id ante sed ex pharetra lacinia sit amet vel massa. Donec facilisis laoreet nulla eu bibendum. Donec ut ex risus. Fusce lorem lectus, pharetra pretium massa et, hendrerit vestibulum odio lorem ipsum.</p>
					<div class="items style1 medium onscroll-fade-in">
						<section>
							<span class="icon style2 major fa-gem"></span>
							<h3><?php echo $areas_list[0]->title ?></h3>
							<p><?php echo $areas_list[0]->abstract ?></p>
						</section>
						<section>
							<span class="icon solid style2 major fa-save"></span>
							<h3><?php echo $areas_list[1]->title ?></h3>
							<p><?php echo $areas_list[1]->abstract ?></p>
						</section>
						<section>
							<span class="icon solid style2 major fa-chart-bar"></span>
							<h3><?php echo $areas_list[2]->title ?></h3>
							<p><?php echo $areas_list[2]->abstract ?></p>
						</section>
						<section>
							<span class="icon solid style2 major fa-wifi"></span>
							<h3><?php echo $areas_list[3]->title ?></h3>
							<p><?php echo $areas_list[3]->abstract ?></p>
						</section>
						<section>
							<span class="icon solid style2 major fa-cog"></span>
							<h3><?php echo $areas_list[4]->title ?></h3>
							<p><?php echo $areas_list[4]->abstract ?></p>
						</section>
						<section>
							<span class="icon style2 major fa-paper-plane"></span>
							<h3>Tempus</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-desktop"></span>
							<h3>Aliquam</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-sync-alt"></span>
							<h3>Elit</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-hashtag"></span>
							<h3>Morbi</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-bolt"></span>
							<h3>Turpis</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-envelope"></span>
							<h3>Ultrices</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
						<section>
							<span class="icon solid style2 major fa-leaf"></span>
							<h3>Risus</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dui turpis, cursus eget orci amet aliquam congue semper. Etiam eget ultrices risus nec tempor elit.</p>
						</section>
					</div>
				</div>
			</section>
			*/ ?>


		<!-- Seven -->
			<?php /*
			<section class="wrapper style1 align-center">
				<div class="inner medium">
					<h2>Get in touch</h2>
					<form method="post" action="#">
						<div class="fields">
							<div class="field half">
								<label for="name">Name</label>
								<input type="text" name="name" id="name" value="" />
							</div>
							<div class="field half">
								<label for="email">Email</label>
								<input type="email" name="email" id="email" value="" />
							</div>
							<div class="field">
								<label for="message">Message</label>
								<textarea name="message" id="message" rows="6"></textarea>
							</div>
						</div>
						<ul class="actions special">
							<li><input type="submit" name="submit" id="submit" value="Send Message" /></li>
						</ul>
					</form>

				</div>
			</section>
			*/?>


		<!-- Footer -->
			<?php echo $this->footer_html ?>
	
	</div>

<?php echo $this->get_header_links('js') ?>
<script type="text/javascript">
	WEB_AREA='<?php echo $this->area_name ?>';
	main_home.setup({})
</script>