<?php
# REQUIRED FILES
$base_path = dirname(dirname(__FILE__));
$cwd        = basename($base_path); # Current dir name

# Current controller add
require($base_path . '/' . $cwd . '.php');
?>
<!-- Page Wrapper -->
<div id="wrapper" class="wrapper style2 align-left">

    <!-- Title -->
    <section class="header_main">
        <header class="major">
            <h1><?php echo $title ?></h1>
        </header>
        <?php echo $abstract ?>
        <?php if(!empty($isbn)) echo '<div>ISBN: ' .$isbn. '</div>' ?>
    </section>

    <!-- Images -->
    <?php if(!empty($ar_image)) { ?>
    <section class="images <?php echo $this->area_table ?> banner onload-image-fade-in">
        <?php foreach ($ar_image as $key => $image) { ?>
            <?php $footer_text = isset($ar_image_footer[$key]) ? $ar_image_footer[$key] : null  ?>
            <a href="<?php echo $image ?>" class="gallery image fit" title="<?php echo $footer_text; ?>">
                <img src="<?php echo $image ?>" alt="" class="image_big"/>
            <?php if(!empty($footer_text)) { ?>
                <span class="image_footer"><?php echo $footer_text; ?></span>
            <?php } ?>
            </a>
            
        <?php } ?>
    </section>
    <?php } ?>



        <div class="wrapper mt-6 flow--xl">
            <div id="items_container"></div>
        </div>

        <!-- Result -->
        <div class="wrapper mt-8 flow--xl" id="rows_list"></div>

    <!-- Footer -->
	<?php echo $this->footer_html ?>
</div>

<?php echo $this->get_header_links('js') ?>
<script>
    dom_ready(function() {
        biblio.set_up({
            rows_list_container: document.getElementById('rows_list')
        })
    })
</script>
