<!-- Footer -->
	<footer class="wrapper style1 align-center">
		<div class="inner">
			<!--<ul class="icons">
				<li><a href="https://twitter.com" target="_blank" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="https://www.facebook.com/" target="_blank" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="https://www.instagram.com/" target="_blank" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
				<li><a href="https://www.linkedin.com/" target="_blank" class="icon brands style2 fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
				<li><a href="#" target="_blank" class="icon style2 fa-envelope"><span class="label">Email</span></a></li>
			</ul>-->

			<p>
				<a href="https://creativecommons.org/licenses/by-nc/3.0/deed.es_ES" title="Creative Commons" target="_blank"><span class="icon brands fa-creative-commons"></span></a> 			
				<?php echo $page_global_body ?>
			</p>
			
			<?php /*<i class="fas fa-cogs"></i> */ ?>
				<a href="http://www.fmomo.org/?lang=es" title="Dédalo site" target="_blank"><img src="<?php echo __WEB_ROOT_WEB__ ?>/tpl/images/dedalo_logo_16.png" width="16" height="16" alt="dedalo" border="0"></a>
        	 	Powered by Dédalo : Cultural Heritage Management Platform
        		
		</div>
	</footer>
