<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!DOCTYPE HTML>
<html>
	<head>
		<title><?php echo $page_title ?></title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
		<link rel='shortcut icon' type='image/x-icon' href='<?php echo __WEB_TEMPLATE_WEB__ ?>/favicon.ico' />
		<link rel="apple-touch-icon" sizes="180x180" href="<?php echo __WEB_TEMPLATE_WEB__ ?>/favicon/apple-touch-icon.png">
		<?php echo $css_links ?>
		<noscript><link rel="stylesheet" href="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">
		<!-- nav -->			
			<?php echo $this->nav_html ?>			

		<!-- Wrapper -->
			<?php echo $content_html ?>

		<!-- Scripts -->
			<?php /*
			<script>WEB_AREA='<?php echo $this->area_name ?>';</script>
			<?php echo $js_links ?>
			*/ ?>
			<?php #include dirname(__FILE__) . '/google_analytics.inc' ?>
	</body>
</html>